apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-client-practice
  labels:
    app: prometheus-client-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-client-practice
  template:
    metadata:
      labels:
        app: prometheus-client-practice
    spec:
      containers:
        - name: prometheus-client-practice
          image: promhello:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-client-practice
  labels:
    app: prometheus-client-practice
spec:
  type: NodePort
  selector:
    app: prometheus-client-practice
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-system
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-client-practice    # 填写一个唯一名称
  namespace: monitoring-system  # namespace固定，不要修改
spec:
  endpoints:
  - interval: 5s
    # 填写service yaml中Prometheus Exporter对应的Port的Name
    port: http
    # 填写Prometheus Exporter对应的Path的值，不填默认/metrics
    path: /metrics
  # 选择要监控service所在的namespace
  namespaceSelector:
    matchNames:
    - default
  # 填写要监控service的Label值，以定位目标service
  selector:
    matchLabels:
      app: prometheus-client-practice